// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/javacup/Lexer.jflex

package javacup;
import java.io.*;
import java_cup.runtime.*;



@SuppressWarnings("fallthrough")
public class Lex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\4"+
    "\1\5\2\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\12\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\40\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\3\40\1\55\1\56\1\57\1\60"+
    "\1\61\1\0\1\27\1\62\1\31\1\32\1\33\1\63"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\64"+
    "\1\45\1\46\1\40\1\65\1\50\1\66\1\52\1\53"+
    "\1\54\3\40\1\67\1\70\1\71\7\0\1\3\252\0"+
    "\2\72\115\0\1\73\u01a8\0\2\3\u0100\0\1\74\325\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\21\23\1\24\1\1"+
    "\1\25\1\26\1\27\1\30\1\1\1\31\21\1\1\32"+
    "\1\0\1\33\1\0\1\34\1\0\1\35\1\0\1\36"+
    "\1\37\1\40\1\0\1\2\1\0\1\41\1\42\1\43"+
    "\1\44\5\23\1\45\4\23\1\0\1\46\3\23\1\0"+
    "\13\23\2\0\1\47\1\46\7\0\1\45\16\0\1\33"+
    "\5\0\1\50\7\23\1\0\2\23\1\51\1\0\1\52"+
    "\2\23\1\0\1\23\1\53\1\23\1\0\6\23\1\0"+
    "\1\23\1\54\1\23\1\0\1\23\3\0\1\52\11\0"+
    "\1\51\2\0\1\53\4\0\1\54\1\0\1\33\1\0"+
    "\1\35\2\0\1\2\1\50\1\23\1\55\1\23\1\56"+
    "\2\23\1\0\1\23\2\57\1\23\1\0\2\60\1\23"+
    "\2\61\2\23\1\0\6\23\1\0\1\23\1\0\1\62"+
    "\2\63\1\23\5\0\1\55\1\0\1\56\7\0\1\62"+
    "\2\0\1\33\3\0\1\2\1\23\2\64\1\65\1\23"+
    "\1\0\1\65\1\23\2\66\1\23\1\67\1\23\1\0"+
    "\2\23\1\70\3\23\1\0\1\23\1\0\2\71\6\0"+
    "\1\67\2\0\1\70\3\0\1\72\1\23\1\0\1\73"+
    "\1\74\1\23\1\0\1\75\1\76\1\0\1\77\1\100"+
    "\1\77\1\23\2\0\1\100\1\72\1\73\1\74\1\75"+
    "\1\76\1\23\1\0\2\101\1\0\1\23\2\0\2\102"+
    "\1\0\2\103\3\0\1\104\44\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[374];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\172\0\u016e"+
    "\0\u01ab\0\172\0\172\0\u01e8\0\u0225\0\172\0\u0262\0\172"+
    "\0\u029f\0\u02dc\0\172\0\172\0\u0319\0\u0356\0\u0393\0\u03d0"+
    "\0\u040d\0\u044a\0\u0487\0\u04c4\0\u0501\0\u053e\0\u057b\0\u05b8"+
    "\0\u05f5\0\u0632\0\u066f\0\u06ac\0\u06e9\0\u0726\0\u0763\0\u07a0"+
    "\0\u07dd\0\u081a\0\172\0\172\0\172\0\172\0\u0857\0\172"+
    "\0\u0894\0\u08d1\0\u029f\0\u090e\0\u094b\0\u0988\0\u09c5\0\u0a02"+
    "\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33\0\u0b70\0\u0bad\0\u0bea"+
    "\0\u0c27\0\172\0\u0c64\0\u0ca1\0\u0cde\0\172\0\u01ab\0\172"+
    "\0\u0d1b\0\172\0\172\0\172\0\u0d58\0\u0d95\0\u0dd2\0\172"+
    "\0\172\0\172\0\172\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6\0\u0f03"+
    "\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u053e\0\u10ae"+
    "\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df\0\u121c\0\u1259\0\u1296"+
    "\0\u12d3\0\u1310\0\u134d\0\u138a\0\u13c7\0\u1404\0\u1441\0\u147e"+
    "\0\172\0\172\0\u14bb\0\u14f8\0\u1535\0\u1572\0\u15af\0\u15ec"+
    "\0\u1629\0\u1666\0\u16a3\0\u16e0\0\u171d\0\u175a\0\u1797\0\u17d4"+
    "\0\u1811\0\u184e\0\u188b\0\u18c8\0\u1905\0\u1942\0\u197f\0\u19bc"+
    "\0\172\0\u19f9\0\u1a36\0\u1a73\0\u1ab0\0\u1aed\0\u1b2a\0\u1b67"+
    "\0\u1ba4\0\u1be1\0\u1c1e\0\u1c5b\0\u1c98\0\u1cd5\0\u1d12\0\u1d4f"+
    "\0\u1d8c\0\u053e\0\u1dc9\0\u053e\0\u1e06\0\u1e43\0\u1e80\0\u1ebd"+
    "\0\u053e\0\u1efa\0\u1f37\0\u1f74\0\u1fb1\0\u1fee\0\u202b\0\u2068"+
    "\0\u20a5\0\u20e2\0\u211f\0\u053e\0\u215c\0\u2199\0\u21d6\0\u2213"+
    "\0\u2250\0\u228d\0\172\0\u22ca\0\u2307\0\u2344\0\u2381\0\u23be"+
    "\0\u23fb\0\u2438\0\u2475\0\u24b2\0\172\0\u24ef\0\u252c\0\172"+
    "\0\u2569\0\u25a6\0\u25e3\0\u2620\0\172\0\u265d\0\u269a\0\u26d7"+
    "\0\u2714\0\u2751\0\u278e\0\172\0\u27cb\0\u2808\0\u053e\0\u2845"+
    "\0\u053e\0\u2882\0\u28bf\0\u28fc\0\u2939\0\u053e\0\172\0\u2976"+
    "\0\u29b3\0\u053e\0\172\0\u29f0\0\u053e\0\172\0\u2a2d\0\u2a6a"+
    "\0\u2aa7\0\u2ae4\0\u2b21\0\u2b5e\0\u2b9b\0\u2bd8\0\u2c15\0\u2c52"+
    "\0\u2c8f\0\u2ccc\0\u053e\0\u053e\0\172\0\u2d09\0\u2d46\0\u2d83"+
    "\0\u2dc0\0\u2dfd\0\u2e3a\0\172\0\u2e77\0\172\0\u2eb4\0\u2ef1"+
    "\0\u2f2e\0\u2f6b\0\u2fa8\0\u2fe5\0\u3022\0\172\0\u269a\0\u305f"+
    "\0\u19f9\0\u309c\0\u2714\0\u30d9\0\u2751\0\u3116\0\u053e\0\172"+
    "\0\u053e\0\u3153\0\u3190\0\172\0\u31cd\0\u053e\0\172\0\u320a"+
    "\0\u053e\0\u3247\0\u3284\0\u32c1\0\u32fe\0\u053e\0\u333b\0\u3378"+
    "\0\u33b5\0\u33f2\0\u342f\0\u346c\0\u053e\0\172\0\u34a9\0\u34e6"+
    "\0\u3523\0\u3560\0\u359d\0\u35da\0\172\0\u3617\0\u3654\0\172"+
    "\0\u3691\0\u36ce\0\u370b\0\u053e\0\u3748\0\u3785\0\u053e\0\u053e"+
    "\0\u37c2\0\u37ff\0\u053e\0\u053e\0\u383c\0\u053e\0\u053e\0\172"+
    "\0\u3879\0\u38b6\0\u38f3\0\172\0\172\0\172\0\172\0\172"+
    "\0\172\0\u3930\0\u396d\0\u053e\0\172\0\u39aa\0\u39e7\0\u3a24"+
    "\0\u3a61\0\u053e\0\172\0\u3a9e\0\u053e\0\172\0\u3adb\0\u3b18"+
    "\0\u3b55\0\172\0\u3b92\0\u3bcf\0\u3c0c\0\u3c49\0\u3c86\0\u3cc3"+
    "\0\u3d00\0\u3d3d\0\u3d7a\0\u3db7\0\u3df4\0\u3e31\0\u3e6e\0\u3eab"+
    "\0\u3ee8\0\u3f25\0\u3f62\0\u3f9f\0\u3fdc\0\u4019\0\u4056\0\u4093"+
    "\0\u40d0\0\u410d\0\u414a\0\u4187\0\u41c4\0\u4201\0\u423e\0\u427b"+
    "\0\u42b8\0\u42f5\0\u4332\0\u436f\0\u43ac\0\u43e9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[374];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\2\36\1\37\2\36\1\40"+
    "\1\41\1\42\1\36\1\43\1\44\1\45\1\46\1\36"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\31"+
    "\1\35\1\42\1\44\1\46\1\56\1\57\1\60\1\61"+
    "\1\62\2\3\2\4\1\0\14\3\1\63\6\3\1\64"+
    "\1\65\1\66\1\67\1\70\1\71\2\3\1\61\2\3"+
    "\1\72\1\73\1\74\1\3\1\75\1\76\1\62\1\77"+
    "\1\3\1\100\1\101\5\3\1\65\1\71\1\74\1\76"+
    "\1\77\3\3\1\61\1\62\1\3\76\0\2\4\117\0"+
    "\1\102\47\0\5\103\1\104\50\103\1\105\16\103\7\0"+
    "\1\106\65\0\10\107\1\110\45\107\1\111\16\107\13\0"+
    "\1\112\75\0\1\113\76\0\1\114\71\0\1\115\4\0"+
    "\1\116\73\0\1\117\1\0\1\22\100\0\1\120\74\0"+
    "\1\121\1\122\73\0\1\123\70\0\1\36\5\0\17\36"+
    "\1\124\6\36\5\0\5\36\27\0\1\36\5\0\16\36"+
    "\1\125\1\36\1\126\5\36\5\0\3\36\1\126\1\36"+
    "\27\0\1\36\5\0\7\36\1\127\6\36\1\130\7\36"+
    "\5\0\5\36\27\0\1\36\5\0\16\36\1\131\7\36"+
    "\5\0\5\36\27\0\1\36\5\0\13\36\1\132\12\36"+
    "\5\0\5\36\27\0\1\36\5\0\1\133\7\36\1\134"+
    "\5\36\1\135\7\36\5\0\5\36\3\0\1\136\23\0"+
    "\1\36\5\0\26\36\5\0\5\36\27\0\1\36\5\0"+
    "\5\36\1\137\7\36\1\140\10\36\5\0\1\36\1\137"+
    "\1\140\2\36\27\0\1\36\5\0\4\36\1\141\3\36"+
    "\1\142\15\36\5\0\5\36\3\0\1\143\23\0\1\36"+
    "\5\0\1\144\25\36\5\0\5\36\27\0\1\36\5\0"+
    "\4\36\1\145\21\36\5\0\5\36\27\0\1\36\5\0"+
    "\20\36\1\146\5\36\5\0\3\36\1\146\1\36\27\0"+
    "\1\36\5\0\4\36\1\147\11\36\1\150\7\36\5\0"+
    "\5\36\27\0\1\36\5\0\22\36\1\151\3\36\5\0"+
    "\4\36\1\151\27\0\1\36\5\0\16\36\1\152\1\36"+
    "\1\153\5\36\5\0\3\36\1\153\1\36\27\0\1\36"+
    "\5\0\1\154\15\36\1\155\7\36\5\0\5\36\27\0"+
    "\1\36\5\0\7\36\1\156\16\36\5\0\5\36\66\0"+
    "\1\157\25\0\1\160\153\0\1\161\40\0\1\162\7\0"+
    "\1\163\16\0\1\162\1\163\61\0\1\164\14\0\1\164"+
    "\54\0\1\165\73\0\1\166\1\0\1\167\15\0\1\167"+
    "\45\0\1\170\6\0\1\171\74\0\1\172\71\0\1\173"+
    "\61\0\1\174\7\0\1\136\5\0\1\175\24\0\1\136"+
    "\35\0\1\176\3\0\1\143\32\0\1\143\31\0\1\177"+
    "\100\0\1\200\110\0\1\201\15\0\1\201\42\0\1\202"+
    "\11\0\1\203\74\0\1\204\1\0\1\205\15\0\1\205"+
    "\36\0\1\206\15\0\1\207\65\0\1\210\36\0\5\103"+
    "\1\211\50\103\1\105\16\103\5\0\1\211\74\0\1\212"+
    "\2\0\1\212\45\0\1\213\3\0\5\212\6\0\10\214"+
    "\1\110\45\214\1\215\16\214\13\115\1\216\61\115\2\116"+
    "\2\0\71\116\21\0\1\217\74\0\1\36\5\0\17\36"+
    "\1\220\6\36\5\0\5\36\27\0\1\36\5\0\16\36"+
    "\1\221\7\36\5\0\5\36\27\0\1\36\5\0\4\36"+
    "\1\222\21\36\5\0\5\36\27\0\1\36\5\0\1\223"+
    "\25\36\5\0\5\36\27\0\1\36\5\0\15\36\1\224"+
    "\10\36\5\0\2\36\1\224\2\36\27\0\1\36\5\0"+
    "\23\36\1\225\2\36\5\0\5\36\27\0\1\36\5\0"+
    "\21\36\1\226\4\36\5\0\5\36\4\0\1\227\22\0"+
    "\1\36\5\0\13\36\1\230\12\36\5\0\5\36\27\0"+
    "\1\36\5\0\15\36\1\231\10\36\5\0\2\36\1\231"+
    "\2\36\27\0\1\36\5\0\20\36\1\232\5\36\5\0"+
    "\3\36\1\232\1\36\52\0\1\233\17\0\1\233\31\0"+
    "\1\36\5\0\22\36\1\234\3\36\5\0\4\36\1\234"+
    "\27\0\1\36\5\0\15\36\1\235\10\36\5\0\2\36"+
    "\1\235\2\36\27\0\1\36\5\0\21\36\1\236\4\36"+
    "\5\0\5\36\4\0\1\237\51\0\1\237\22\0\1\237"+
    "\22\0\1\36\5\0\22\36\1\240\3\36\5\0\4\36"+
    "\1\240\27\0\1\36\5\0\25\36\1\241\5\0\5\36"+
    "\27\0\1\36\5\0\10\36\1\242\15\36\5\0\5\36"+
    "\3\0\1\243\23\0\1\36\5\0\14\36\1\244\5\36"+
    "\1\245\3\36\5\0\4\36\1\245\27\0\1\36\5\0"+
    "\23\36\1\246\2\36\5\0\5\36\27\0\1\36\5\0"+
    "\1\247\17\36\1\250\5\36\5\0\3\36\1\250\1\36"+
    "\27\0\1\36\5\0\21\36\1\251\4\36\5\0\5\36"+
    "\4\0\1\252\22\0\1\36\5\0\23\36\1\253\2\36"+
    "\5\0\5\36\27\0\1\36\5\0\20\36\1\254\5\36"+
    "\5\0\3\36\1\254\1\36\27\0\1\36\5\0\10\36"+
    "\1\255\15\36\5\0\5\36\3\0\1\256\23\0\1\36"+
    "\5\0\10\36\1\257\15\36\5\0\5\36\3\0\1\260"+
    "\61\0\1\261\26\0\1\262\134\0\1\263\14\0\1\263"+
    "\35\0\1\264\17\0\1\265\15\0\1\265\55\0\1\266"+
    "\73\0\1\267\62\0\1\270\70\0\1\271\111\0\1\272"+
    "\17\0\1\272\62\0\1\273\72\0\1\227\22\0\1\227"+
    "\43\0\1\274\101\0\1\275\15\0\1\275\53\0\1\276"+
    "\17\0\1\276\61\0\1\277\14\0\1\277\62\0\1\300"+
    "\57\0\1\243\32\0\1\243\45\0\1\301\5\0\1\302"+
    "\14\0\1\302\60\0\1\303\72\0\1\252\22\0\1\252"+
    "\53\0\1\304\71\0\1\305\15\0\1\305\46\0\1\256"+
    "\32\0\1\256\41\0\1\260\32\0\1\260\2\0\5\212"+
    "\1\211\50\212\1\306\16\212\2\103\2\212\1\103\1\307"+
    "\50\103\1\310\16\103\10\214\1\110\64\214\2\107\2\214"+
    "\4\107\1\311\64\107\13\312\1\313\4\312\1\314\54\312"+
    "\21\0\1\315\74\0\1\36\5\0\4\36\1\316\21\36"+
    "\5\0\5\36\27\0\1\36\5\0\13\36\1\317\12\36"+
    "\5\0\5\36\27\0\1\36\5\0\1\320\25\36\5\0"+
    "\5\36\27\0\1\36\5\0\20\36\1\321\5\36\5\0"+
    "\3\36\1\321\1\36\27\0\1\36\5\0\21\36\1\322"+
    "\1\323\3\36\5\0\4\36\1\323\4\0\1\324\22\0"+
    "\1\36\5\0\1\36\1\325\24\36\5\0\1\325\4\36"+
    "\27\0\1\36\5\0\4\36\1\326\21\36\5\0\5\36"+
    "\41\0\1\327\62\0\1\36\5\0\21\36\1\330\4\36"+
    "\5\0\5\36\4\0\1\331\22\0\1\36\5\0\3\36"+
    "\1\332\22\36\5\0\5\36\40\0\1\333\63\0\1\36"+
    "\5\0\6\36\1\334\17\36\5\0\5\36\27\0\1\36"+
    "\5\0\22\36\1\335\3\36\5\0\4\36\1\335\57\0"+
    "\1\336\14\0\1\336\27\0\1\36\5\0\2\36\1\337"+
    "\23\36\5\0\5\36\27\0\1\36\5\0\15\36\1\340"+
    "\10\36\5\0\2\36\1\340\2\36\52\0\1\341\17\0"+
    "\1\341\31\0\1\36\5\0\16\36\1\342\7\36\5\0"+
    "\5\36\27\0\1\36\5\0\23\36\1\343\2\36\5\0"+
    "\5\36\27\0\1\36\5\0\15\36\1\344\10\36\5\0"+
    "\2\36\1\344\2\36\27\0\1\36\5\0\20\36\1\345"+
    "\5\36\5\0\3\36\1\345\1\36\27\0\1\36\5\0"+
    "\10\36\1\346\12\36\1\347\2\36\5\0\5\36\3\0"+
    "\1\350\23\0\1\36\5\0\22\36\1\351\3\36\5\0"+
    "\4\36\1\351\57\0\1\352\14\0\1\352\27\0\1\36"+
    "\5\0\4\36\1\353\21\36\5\0\5\36\27\0\1\36"+
    "\5\0\3\36\1\354\22\36\5\0\5\36\40\0\1\355"+
    "\63\0\1\36\5\0\13\36\1\356\12\36\5\0\5\36"+
    "\50\0\1\357\45\0\1\211\136\0\1\360\66\0\1\361"+
    "\15\0\1\361\46\0\1\350\12\0\1\362\17\0\1\350"+
    "\35\0\1\363\103\0\1\364\61\0\1\365\114\0\1\366"+
    "\15\0\1\366\57\0\1\324\1\367\14\0\1\367\4\0"+
    "\1\324\31\0\1\370\31\0\1\370\62\0\1\331\22\0"+
    "\1\331\36\0\1\371\70\0\1\372\110\0\1\373\101\0"+
    "\1\374\66\0\1\375\17\0\1\375\43\0\1\376\46\0"+
    "\1\212\2\0\1\212\45\0\1\212\3\0\5\212\6\0"+
    "\5\377\1\211\50\377\1\u0100\23\377\1\u0101\2\377\1\103"+
    "\45\377\1\u0102\3\377\5\103\6\377\10\u0103\1\110\45\u0103"+
    "\1\u0104\16\u0103\13\312\1\313\74\312\1\313\4\312\1\u0105"+
    "\54\312\17\0\1\117\1\0\1\315\74\0\1\36\5\0"+
    "\15\36\1\u0106\10\36\5\0\2\36\1\u0106\2\36\27\0"+
    "\1\36\5\0\12\36\1\u0107\13\36\5\0\5\36\5\0"+
    "\1\u0108\21\0\1\36\5\0\22\36\1\u0109\3\36\5\0"+
    "\4\36\1\u0109\27\0\1\36\5\0\10\36\1\u010a\15\36"+
    "\5\0\5\36\3\0\1\u010b\53\0\1\u010c\14\0\1\u010c"+
    "\27\0\1\36\5\0\13\36\1\u010d\12\36\5\0\5\36"+
    "\27\0\1\36\5\0\4\36\1\u010e\21\36\5\0\5\36"+
    "\41\0\1\u010f\62\0\1\36\5\0\22\36\1\u0110\3\36"+
    "\5\0\4\36\1\u0110\27\0\1\36\5\0\7\36\1\u0111"+
    "\16\36\5\0\5\36\27\0\1\36\5\0\22\36\1\u0112"+
    "\3\36\5\0\4\36\1\u0112\57\0\1\u0113\14\0\1\u0113"+
    "\27\0\1\36\5\0\24\36\1\u0114\1\36\5\0\5\36"+
    "\27\0\1\36\5\0\20\36\1\u0115\5\36\5\0\3\36"+
    "\1\u0115\1\36\27\0\1\36\5\0\3\36\1\u0116\22\36"+
    "\5\0\5\36\27\0\1\36\5\0\22\36\1\u0117\3\36"+
    "\5\0\4\36\1\u0117\27\0\1\36\5\0\15\36\1\u0118"+
    "\10\36\5\0\2\36\1\u0118\2\36\27\0\1\36\5\0"+
    "\2\36\1\u0119\23\36\5\0\5\36\52\0\1\u011a\17\0"+
    "\1\u011a\31\0\1\36\5\0\20\36\1\u011b\5\36\5\0"+
    "\3\36\1\u011b\1\36\55\0\1\u011c\15\0\1\u011c\30\0"+
    "\1\36\5\0\4\36\1\u011d\21\36\5\0\5\36\41\0"+
    "\1\u011e\121\0\1\u011f\65\0\1\u0120\14\0\1\u0120\37\0"+
    "\1\u0121\107\0\1\u0122\17\0\1\u0122\51\0\1\u0108\32\0"+
    "\1\u0108\37\0\1\u010b\32\0\1\u010b\44\0\1\u0123\103\0"+
    "\1\u0124\14\0\1\u0124\44\0\1\u0125\111\0\1\u0126\70\0"+
    "\1\u0127\15\0\1\u0127\41\0\1\u0128\120\0\1\u0129\16\0"+
    "\5\212\1\211\50\212\1\u012a\16\212\56\0\1\u012b\37\0"+
    "\1\36\5\0\3\36\1\u012c\22\36\5\0\5\36\27\0"+
    "\1\36\5\0\15\36\1\u012d\10\36\5\0\2\36\1\u012d"+
    "\2\36\52\0\1\u012e\17\0\1\u012e\31\0\1\36\5\0"+
    "\4\36\1\u012f\21\36\5\0\5\36\27\0\1\36\5\0"+
    "\7\36\1\u0130\16\36\5\0\5\36\27\0\1\36\5\0"+
    "\13\36\1\u0131\12\36\5\0\5\36\50\0\1\u0132\53\0"+
    "\1\36\5\0\4\36\1\u0133\21\36\5\0\5\36\27\0"+
    "\1\36\5\0\15\36\1\u0134\10\36\5\0\2\36\1\u0134"+
    "\2\36\27\0\1\36\5\0\26\36\4\0\1\u0135\5\36"+
    "\27\0\1\36\5\0\6\36\1\u0136\17\36\5\0\5\36"+
    "\27\0\1\36\5\0\22\36\1\u0137\3\36\5\0\4\36"+
    "\1\u0137\43\0\1\u0138\60\0\1\36\5\0\10\36\1\u0139"+
    "\15\36\5\0\5\36\3\0\1\u013a\41\0\1\u013a\32\0"+
    "\1\u013a\7\0\1\u013b\150\0\1\u0135\64\0\1\u013c\14\0"+
    "\1\u013c\40\0\1\u013d\75\0\1\u013e\77\0\1\u013f\71\0"+
    "\1\u0140\105\0\1\u0141\17\0\1\u0141\10\0\2\377\2\0"+
    "\73\377\2\0\1\377\1\103\2\377\1\103\45\377\1\103"+
    "\3\377\5\103\6\377\2\u0103\2\0\71\u0103\21\0\1\36"+
    "\5\0\23\36\1\u0142\2\36\5\0\5\36\60\0\1\u0143"+
    "\43\0\1\36\5\0\15\36\1\u0144\10\36\5\0\2\36"+
    "\1\u0144\2\36\52\0\1\u0145\17\0\1\u0145\64\0\1\u0146"+
    "\41\0\1\36\5\0\15\36\1\u0147\10\36\5\0\2\36"+
    "\1\u0147\2\36\52\0\1\u0148\17\0\1\u0148\66\0\1\u0149"+
    "\37\0\1\36\5\0\4\36\1\u014a\21\36\5\0\5\36"+
    "\41\0\1\u014b\100\0\1\u014c\32\0\1\u014c\23\0\1\36"+
    "\5\0\6\36\1\u014d\17\36\5\0\5\36\43\0\1\u014e"+
    "\115\0\1\u014f\67\0\1\u0150\14\0\1\u0150\52\0\1\u0151"+
    "\17\0\1\u0151\46\0\1\u0152\115\0\1\u0153\105\0\1\u0154"+
    "\62\0\1\u0155\74\0\1\u0156\62\0\1\u0157\17\0\1\u0157"+
    "\100\0\1\u0158\62\0\1\u0159\74\0\1\u015a\74\0\1\u015b"+
    "\74\0\1\u015c\62\0\1\u015d\17\0\1\u015d\100\0\1\u015e"+
    "\62\0\1\u015f\74\0\1\u0160\23\0\1\u0161\74\0\1\u0162"+
    "\157\0\1\u0163\62\0\1\u0164\74\0\1\u0165\74\0\1\u0166"+
    "\74\0\1\u0167\62\0\1\u0168\17\0\1\u0168\100\0\1\u0169"+
    "\62\0\1\u016a\74\0\1\u016b\35\0\1\u016c\132\0\1\u016d"+
    "\77\0\1\u016e\21\0\1\u016f\145\0\1\u0170\74\0\1\u0171"+
    "\62\0\1\u0172\17\0\1\u0172\67\0\1\u0173\27\0\1\u0174"+
    "\75\0\1\u0175\73\0\1\u0176\140\0\1\211\16\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[17446];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\1\11\2\1\2\11\2\1\1\11"+
    "\1\1\1\11\2\1\2\11\26\1\4\11\1\1\1\11"+
    "\21\1\1\11\1\0\1\1\1\0\1\11\1\0\1\11"+
    "\1\0\3\11\1\0\1\1\1\0\4\11\12\1\1\0"+
    "\4\1\1\0\13\1\2\0\2\11\7\0\1\1\16\0"+
    "\1\11\5\0\10\1\1\0\3\1\1\0\3\1\1\0"+
    "\3\1\1\0\6\1\1\0\3\1\1\0\1\1\3\0"+
    "\1\11\11\0\1\11\2\0\1\11\4\0\1\11\1\0"+
    "\1\1\1\0\1\1\2\0\1\11\7\1\1\0\2\1"+
    "\1\11\1\1\1\0\1\1\1\11\2\1\1\11\2\1"+
    "\1\0\6\1\1\0\1\1\1\0\2\1\1\11\1\1"+
    "\5\0\1\11\1\0\1\11\7\0\1\11\2\0\1\1"+
    "\3\0\3\1\1\11\2\1\1\0\1\11\2\1\1\11"+
    "\3\1\1\0\6\1\1\0\1\1\1\0\1\1\1\11"+
    "\6\0\1\11\2\0\1\11\3\0\2\1\1\0\3\1"+
    "\1\0\2\1\1\0\2\1\1\11\1\1\2\0\6\11"+
    "\1\1\1\0\1\1\1\11\1\0\1\1\2\0\1\1"+
    "\1\11\1\0\1\1\1\11\3\0\1\11\44\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[374];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();
	
	private Symbol Symbol(int type){
		return new Symbol(type, yyline, yycolumn);
	}
	private Symbol Symbol(int type, Object value){
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lex(java.io.Reader in) {
      yyline=1;
    yycolumn=1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Warning: unrecognized character " + yytext());
            }
          // fall through
          case 69: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 70: break;
          case 3:
            { return new Symbol (sym.NOT, yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 4:
            { return new Symbol (sym.MODULO, yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 5:
            { return new Symbol (sym.PARENABRE, yyline, yycolumn,yytext());
            }
          // fall through
          case 73: break;
          case 6:
            { return new Symbol (sym.PARENCIERRA, yyline, yycolumn,yytext());
            }
          // fall through
          case 74: break;
          case 7:
            { return new Symbol (sym.MULTIPLICACION, yyline, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 8:
            { return new Symbol (sym.SUMA, yyline,yycolumn,yytext());
            }
          // fall through
          case 76: break;
          case 9:
            { return new Symbol (sym.COMA, yyline, yycolumn,yytext());
            }
          // fall through
          case 77: break;
          case 10:
            { return new Symbol (sym.MENOS, yyline,yycolumn,yytext());
            }
          // fall through
          case 78: break;
          case 11:
            { return new Symbol (sym.PUNTO, yyline, yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 12:
            { return new Symbol (sym.DIVISION, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 13:
            { return new Symbol (sym.ENTERO, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 14:
            { return new Symbol (sym.DP, yyline, yycolumn,yytext());
            }
          // fall through
          case 82: break;
          case 15:
            { return new Symbol (sym.PYC, yyline, yycolumn,yytext());
            }
          // fall through
          case 83: break;
          case 16:
            { return new Symbol (sym.MENORQ, yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 17:
            { return new Symbol (sym.IGUAL, yyline,yycolumn,yytext());
            }
          // fall through
          case 85: break;
          case 18:
            { return new Symbol (sym.MAYORQ, yyline, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 19:
            { return new Symbol (sym.ID, yyline,yycolumn,yytext());
            }
          // fall through
          case 87: break;
          case 20:
            { return new Symbol (sym.CORCHABRE, yyline, yycolumn,yytext());
            }
          // fall through
          case 88: break;
          case 21:
            { return new Symbol (sym.CORCHCIERRA, yyline, yycolumn,yytext());
            }
          // fall through
          case 89: break;
          case 22:
            { return new Symbol (sym.XOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 23:
            { return new Symbol (sym.DEFAULT, yyline, yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 24:
            { return new Symbol (sym.LLAVEABRE, yyline, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 25:
            { return new Symbol (sym.LLAVECIERRA, yyline, yycolumn, yytext());
            }
          // fall through
          case 93: break;
          case 26:
            { return new Symbol (sym.DIFERENTE, yyline, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 27:
            { return new Symbol (sym.STRING, yyline, yycolumn,yytext());
            }
          // fall through
          case 95: break;
          case 28:
            { return new Symbol (sym.AND, yyline, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 29:
            { return new Symbol (sym.TKCHAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 30:
            { return new Symbol (sym.POTENCIA, yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 31:
            { return new Symbol (sym.INC, yyline, yycolumn, yytext());
            }
          // fall through
          case 99: break;
          case 32:
            { return new Symbol (sym.DEC, yyline, yycolumn, yytext());
            }
          // fall through
          case 100: break;
          case 33:
            { return new Symbol (sym.MENORIGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 101: break;
          case 34:
            { return new Symbol (sym.IGUALACION, yyline, yycolumn, yytext());
            }
          // fall through
          case 102: break;
          case 35:
            { return new Symbol (sym.ARROW, yyline, yycolumn, yytext());
            }
          // fall through
          case 103: break;
          case 36:
            { return new Symbol (sym.MAYORIGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 104: break;
          case 37:
            { return new Symbol (sym.DO, yyline, yycolumn, yytext());
            }
          // fall through
          case 105: break;
          case 38:
            { return new Symbol (sym.TKIF, yyline, yycolumn, yytext());
            }
          // fall through
          case 106: break;
          case 39:
            { return new Symbol (sym.OR, yyline, yycolumn, yytext());
            }
          // fall through
          case 107: break;
          case 40:
            { return new Symbol (sym.DECIMAL, yyline, yycolumn,yytext());
            }
          // fall through
          case 108: break;
          case 41:
            { return new Symbol (sym.FOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 109: break;
          case 42:
            { return new Symbol (sym.INT, yyline, yycolumn, yytext());
            }
          // fall through
          case 110: break;
          case 43:
            { return new Symbol (sym.NEW, yyline, yycolumn, yytext());
            }
          // fall through
          case 111: break;
          case 44:
            { return new Symbol (sym.VAR, yyline, yycolumn,yytext());
            }
          // fall through
          case 112: break;
          case 45:
            { return new Symbol (sym.BOOL, yyline, yycolumn, yytext());
            }
          // fall through
          case 113: break;
          case 46:
            { return new Symbol (sym.CHAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 114: break;
          case 47:
            { return new Symbol (sym.ELSE, yyline, yycolumn, yytext());
            }
          // fall through
          case 115: break;
          case 48:
            { return new Symbol (sym.FIND, yyline, yycolumn, yytext());
            }
          // fall through
          case 116: break;
          case 49:
            { return new Symbol (sym.LIST, yyline, yycolumn, yytext());
            }
          // fall through
          case 117: break;
          case 50:
            { return new Symbol (sym.TRUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 118: break;
          case 51:
            { return new Symbol (sym.TKVOID, yyline, yycolumn, yytext());
            }
          // fall through
          case 119: break;
          case 52:
            { return new Symbol (sym.TKBREAK, yyline, yycolumn, yytext());
            }
          // fall through
          case 120: break;
          case 53:
            { return new Symbol (sym.CONST, yyline, yycolumn, yytext());
            }
          // fall through
          case 121: break;
          case 54:
            { return new Symbol (sym.FALSE, yyline, yycolumn, yytext());
            }
          // fall through
          case 122: break;
          case 55:
            { return new Symbol (sym.MATCH, yyline, yycolumn, yytext());
            }
          // fall through
          case 123: break;
          case 56:
            { return new Symbol (sym.ROUND, yyline, yycolumn, yytext());
            }
          // fall through
          case 124: break;
          case 57:
            { return new Symbol (sym.WHILE, yyline, yycolumn, yytext());
            }
          // fall through
          case 125: break;
          case 58:
            { return new Symbol (sym.APPEND, yyline, yycolumn, yytext());
            }
          // fall through
          case 126: break;
          case 59:
            { return new Symbol (sym.DOUBLE,yyline, yycolumn,yytext());
            }
          // fall through
          case 127: break;
          case 60:
            { return new Symbol (sym.LEN, yyline, yycolumn, yytext());
            }
          // fall through
          case 128: break;
          case 61:
            { return new Symbol (sym.REMOVE, yyline, yycolumn, yytext());
            }
          // fall through
          case 129: break;
          case 62:
            { return new Symbol (sym.TKRETURN, yyline, yycolumn, yytext());
            }
          // fall through
          case 130: break;
          case 63:
            { return new Symbol (sym.TKSTRING, yyline, yycolumn, yytext());
            }
          // fall through
          case 131: break;
          case 64:
            { return new Symbol (sym.TKSTRUCT, yyline, yycolumn, yytext());
            }
          // fall through
          case 132: break;
          case 65:
            { return new Symbol (sym.PRINTLN, yyline, yycolumn, yytext());
            }
          // fall through
          case 133: break;
          case 66:
            { return new Symbol (sym.TKCONTINUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 134: break;
          case 67:
            { return new Symbol (sym.TOSTRING, yyline, yycolumn, yytext());
            }
          // fall through
          case 135: break;
          case 68:
            { return new Symbol (sym.TKSTART, yyline, yycolumn, yytext());
            }
          // fall through
          case 136: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
