
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package javacup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ARROBAID = 11;
  public static final int CONST = 24;
  public static final int CHAR = 6;
  public static final int IGUALACION = 15;
  public static final int MENORQ = 35;
  public static final int ENTERO = 47;
  public static final int XOR = 27;
  public static final int DIFERENTE = 16;
  public static final int DOUBLE = 7;
  public static final int PARENABRE = 37;
  public static final int INT = 12;
  public static final int PRINTLN = 3;
  public static final int TKIF = 52;
  public static final int FOR = 53;
  public static final int MATCH = 55;
  public static final int NOT = 28;
  public static final int MENORIGUAL = 17;
  public static final int AND = 26;
  public static final int IGUAL = 22;
  public static final int CORCHABRE = 39;
  public static final int OR = 25;
  public static final int BOOL = 13;
  public static final int INC = 51;
  public static final int SUMA = 9;
  public static final int UMENOS = 31;
  public static final int ID = 42;
  public static final int MAYORIGUAL = 18;
  public static final int EOF = 0;
  public static final int DECIMAL = 29;
  public static final int RETURN = 57;
  public static final int TKBREAK = 59;
  public static final int TRUE = 43;
  public static final int error = 1;
  public static final int COMA = 2;
  public static final int MODULO = 21;
  public static final int MENOS = 10;
  public static final int TKCONTINUE = 60;
  public static final int TKSTRING = 30;
  public static final int REASIGN = 23;
  public static final int POTENCIA = 20;
  public static final int ARROW = 48;
  public static final int ELSE = 54;
  public static final int MAYORQ = 36;
  public static final int WHILE = 56;
  public static final int DEFAULT = 49;
  public static final int ASIGN = 32;
  public static final int END = 5;
  public static final int UNDERSCORE = 41;
  public static final int STRING = 46;
  public static final int DEC = 50;
  public static final int FALSE = 44;
  public static final int TKCHAR = 45;
  public static final int DIVISION = 19;
  public static final int PARENCIERRA = 38;
  public static final int VAR = 8;
  public static final int DP = 34;
  public static final int DO = 58;
  public static final int CONSOLE = 4;
  public static final int PYC = 33;
  public static final int MULTIPLICACION = 14;
  public static final int CORCHCIERRA = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "PRINTLN",
  "CONSOLE",
  "END",
  "CHAR",
  "DOUBLE",
  "VAR",
  "SUMA",
  "MENOS",
  "ARROBAID",
  "INT",
  "BOOL",
  "MULTIPLICACION",
  "IGUALACION",
  "DIFERENTE",
  "MENORIGUAL",
  "MAYORIGUAL",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "IGUAL",
  "REASIGN",
  "CONST",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "DECIMAL",
  "TKSTRING",
  "UMENOS",
  "ASIGN",
  "PYC",
  "DP",
  "MENORQ",
  "MAYORQ",
  "PARENABRE",
  "PARENCIERRA",
  "CORCHABRE",
  "CORCHCIERRA",
  "UNDERSCORE",
  "ID",
  "TRUE",
  "FALSE",
  "TKCHAR",
  "STRING",
  "ENTERO",
  "ARROW",
  "DEFAULT",
  "DEC",
  "INC",
  "TKIF",
  "FOR",
  "ELSE",
  "MATCH",
  "WHILE",
  "RETURN",
  "DO",
  "TKBREAK",
  "TKCONTINUE"
  };
}

